{% set name = "globus-automate-client" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f10591429ccbdbf6e2f066c2bdae7bf52d4c816e2b67612cef79c4a141d67c88

build:
  entry_points:
    - globus-automate = globus_automate_client.cli.main:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.0.0
  run:
    - arrow >=1.1,<2.0.0
    - globus-sdk >=3.1,<4.0
    - python-graphviz >=0.12,<0.13
    - jsonschema >=3.2,<4.0.0
    - python >={{ python_min }},<4.0.0
    - pyyaml >=6.0,<7.0.0
    - rich >=13.9,<14.0.0
    - typer >=0.4,<0.5.0
    - typing-extensions >=4.1,<5.0.0

test:
  imports:
    - globus_automate_client
  commands:
    - pip check
    - globus-automate --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/globus-automate-client/
  summary: Client for the Globus Flows service
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
